version: "3"

services:
  mongoui-backend:
    container_name: c_mongoui_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6060:6060"
    restart: unless-stopped
    networks:
      - project_network

networks:
  project_network:
    external: true